services:
  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1532"
      POSTGRES_DB: weblab2
    volumes:
      - ./db/dump:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: on-failure # Политика перезапуска для базы данных

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      DATABASE_URL: "postgresql://postgres:1532@db:5432/weblab2"
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dump:
    external: false